name: Create Pull Request For Google Analytics Plugin Based on Input Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ga-pr-create-token:
        required: true

jobs:
  Bump-Version-And-Create-PR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b bot
          git branch
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: bump version
        run: |
          echo ${{inputs.tag}} && python3 bin/bump_version.py ${{inputs.tag}}
      - name: commit
        run: |
          # Stage the file, commit and push
          git branch
          git status
          git add -A
          git commit -m "auto commit"
      - name: create pr
        run: gh pr create -B main -H bot --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.ga-pr-create-token }}
#        uses: peter-evans/create-pull-request@v4
#        with:
#          token: ${{ secrets.ga-pr-create-token }}
#          base: main
#          commit-message: Bump Version to ${{inputs.tag}}
#          committer: GitHub <noreply@github.com>
#          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#          assignees: BionIT
#          reviewers: BionIT



