name: Scheduled Build and Release for Google Analytics Plugin

on:
  push:
    branches: [ scheduled-build ]
  # Adds workflow_dispatch for manually running a workflow
  workflow_dispatch:
  # Adds schdeule event trigger for daily reset.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # Run daily at 04:30 UTC.
    - cron:  '30 04 * * *'
jobs:
  Schedule-Check-On-OSD-Release:
    runs-on: ubuntu-latest
    outputs:
      osd_tag: ${{steps.osd.outputs.release}}
      ga_tag: ${{steps.ga.outputs.release}}
    steps:
      - id: osd
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: opensearch-project/OpenSearch-Dashboards
      - run: echo ${{steps.osd.outputs.release}}
      - id: ga
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: BionIT/google-analytics-plugin
      - run: echo ${{steps.ga.outputs.release}}

  Create-Pull-Request:
    needs: Schedule-Check-On-OSD-Release
    if: ${{ needs.Schedule-Check-On-OSD-Release.outputs.osd_tag == needs.Schedule-Check-On-OSD-Release.outputs.ga_tag }}
    uses: BionIT/google-analytics-plugin/.github/workflows/bump-version-create-pr.yml@scheduled-build
    with:
      tag: ${{needs.Schedule-Check-On-OSD-Release.outputs.osd_tag}}
    secrets:
      ga-pr-create-token: ${{secrets.GA_PR_CREATE_TOKEN}}

