name: Scheduled Build and Release for Google Analytics Plugin

on:
  push:
    branches: [ main ]
  # Adds workflow_dispatch for manually running a workflow
  workflow_dispatch:
  # Adds schdeule event trigger for daily reset.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # Run daily at 04:30 UTC.
    - cron:  '30 04 * * *'
jobs:
  Schedule-Check-On-OSD-Release:
    name: latestRelease
    runs-on: ubuntu-latest
    steps:
      - id: osd
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: opensearch-project/OpenSearch-Dashboards
      - run: echo ${{steps.osd.outputs.release}}
      - id: ga
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: BionIT/google-analytics-plugin
      - run: echo ${{steps.ga.outputs.release}}
      - if: ${{steps.osd.outputs.release == steps.ga.outputs.release }}
        uses: BionIT/google-analytics-plugin/.github/workflows/build-and-release.yml@scheduled-build
        with:
          tag: ${{steps.osd.outputs.release}}
      - run: echo "Completed"

